// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODO.DAL;

namespace TODO.DAL.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TODO.Model.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2021, 2, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Shopping",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2021, 2, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Meeting",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2021, 2, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Health Checkup",
                            Priority = "Medium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
